---
title: "Replication Report for Experiments 1 and 5 by Wal et al. (2021, Nature Communications)"
author: "Alice Xue (alicexue@stanford.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

How does the hippocampus - a subcortical brain structure - support episodic memory encoding and retrieval? I am interested in studying how theta oscillations in the hippocampus play a role in these memory processes. Computational models of information processing in the hippocampus make predictions about when encoding and retrieval may take place optimally with respect to different phases of the hippocampal theta rhythm. These rhythmic neural processes may have downstream consequences on behavior, a prediction tested by Wal et al. (2021). They assessed whether the timing of behavioral responses is rhythmic in memory-dependent vs. memory-independent (visual) tasks. In addition, they looked at theta rhythmicity in intracranial EEG recordings, which will be ignored in the current behavioral replication study.

### Justification for choice of study

I am interested in rhythms in cognition, and am curious about the reliability of the interesting behavioral effects reported in this paper. By attempting to replicate this study, I will learn a great deal about the analysis approach the authors developed; this will be useful for understanding different ways of studying behavioral/neural rhythms and may be useful for my own research. 

### Anticipated challenges

I expect that data analysis will be the main challenge for me in conducting this replication project, as the computation of the Oscillation score appears to be rather complex. I aim to recreate the authors' Matlab code (provided on GitHub) in R, a language I am not particularly comfortable with. 

### Links

Project repository (on Github): https://github.com/psych251/wal2021.git

Original paper (as hosted in your repo): https://github.com/psych251/wal2021/blob/main/original_paper/Wal2021_NatComms.pdf


## Methods

### Description of the steps required to replicate the results

I will need to identify and collect the word and picture stimuli that the authors used for the behavioral tasks in their paper.

In the memory-dependent task (Experiment 5), participants take part in an encoding phase, a distractor phase, and a retrieval phase in multiple blocks. In the encoding phase, participants  associate a word with an object (presented at different times; 128 associations total), and indicate with a button press when they have successfully encoded the association. In the distractor phase, they judge whether numbers displayed on the screen are odd or even (for one minute). In the retrieval (with-catch) phase, they are presented a semantic/perceptual question (“animate or inanimate?” / “photo or drawing?”), followed a word probe. Participants are instructed to recall whether the associated image was animate/inanimate or a photo/drawing (or if they forgot), and make their response with a button press. 

In the memory-independent (visual) task (Experiment 1), participants are first presented with a semantic/perceptual question (“animate or inanimate?” / “photo or drawing?”). This is followed by the presentation of an object, during which time the participants provide their response with a button press.

For each task (encoding, retrieval, visual), I will compute an Oscillation score using the procedures described in the paper and as implemented in the Matlab code the authors provided on GitHub (although I will recreate this code in R to better understand the analysis procedure and become more comfortable with R).

### Differences from original study

The original study had several experiments. My goal is to replicate two of the behavioral ones (as my key analysis depends on a comparison between a memory-based and visual control task that they ran in two separate samples of participants). A major difference is that all of their experiments were conducted in person, whereas mine will be conducted online (on Prolific). I anticipate that online participants may be less attentive and more likely to rush through the study; this could affect reaction times, a key dependent variable in the analyses. 

There are additionally software differences with respect to task presentation; I will be using jsPsych to present each task, while the original authors used PsychToolBox. There could be slight differences in stimulus presentation timing, but I do not think these will influence my results. 

On the analysis side, my code will be in R, whereas their was in Matlab. I do not yet know if this will influence my ability to replicate the original results.

My study will likely be very underpowered in comparison to the study in the original paper, especially since they had multiple experiments with slightly different tasks/stimuli in each experiment. The effect size may have been larger in certain variations of their experiments, but I do not know for sure. I decided to replicate the two behavioral experiments that they conducted in healthy individuals, and in which they used "Standard" stimuli.

### Power Analysis

Original effect size, power analysis for samples to achieve 80%, 90%, 95% power to detect that effect size.  Considerations of feasibility for selecting planned sample size.

### Planned Sample

Planned sample size and/or termination rule, sampling frame, known demographics if any, preselection rules if any.

### Materials

All materials - can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Procedure	

Can quote directly from original article - just put the text in quotations and note that this was followed precisely.  Or, quote directly and just point out exceptions to what was described in the original article.

### Analysis Plan

Can also quote directly, though it is less often spelled out effectively for an analysis strategy section.  The key is to report an analysis strategy that is as close to the original - data cleaning rules, data exclusion rules, covariates, etc. - as possible.  

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
###Data Preparation

####Load Relevant Libraries and Functions

####Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
